sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: <$+上一步Travis CI设置里的tokon名，例如 $token>
    on:
        branch: master
    local_dir: public
    repo: logwood/logwood.github.io
    fqdn: zlog.fun
    target_branch: master
    email: logwood.yu@gmail.com
    name: logwood